name: GR Mailsource

on:
  workflow_call:
    inputs:
      GAROON_VERSION:
        required: true
        type: string

jobs:
  test:
    steps:
      - run: echo ${{ github.event.inputs.GAROON_VERSION }}
