name: GR Mailsource

on:
  workflow_call:
    inputs:
      GAROON_VERSION:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.GAROON_VERSION }}
