name: GR Mailsource
run-name: ${{ env["0 21 * * 1-4,0"] }} - Test

env:
  - "0 21 * * 1-4,0": "F23.5"
  - "0 21 * * 1-4,0": "F23.7"

on:
  workflow_call:
    inputs:
      GAROON_VERSION:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: datdo178/github-actions
          ref: test
      - run: echo "${{ inputs.GAROON_VERSION }}"
      - run: ls
