name: Mail test - F23.6

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Environment Variables
        uses: xom9ikk/dotenv@v2
        with:
          path: ./.github/workflows/env
          mode: 23.6
      - name: Deploy with specific archive
        if: ${{env.force_recreate_service_set == 'true' && env.FOLDER && env.ARCHIVE}}
        run: echo "${{env.BRANCH}}"
