name: Regression
run-name: ${{ github.actor }} 🚀 - Regression

on:
  schedule:
    - cron: '0 10 * * 1-5'
    - cron: '0 12 * * 1-5'
  workflow_dispatch:
    inputs:
      SPECIFIC_TESTING_BRANCH:
        required: false
        description: 'SPECIFIC_TESTING_BRANCH - If you select an options for this variable, you can ignore inputting value for variables below (the default values for the selected options will be applied)'
        default: 'None'
        type: 'choice'
        options:
          - 'None'
          - 'F23.5'
          - 'F23.6'
      ADMIN_USERNAME:
        type: string
      PASSWORD:
        type: string
      SERVICE_SET:
        type: string
      TESTING_HOST:
        type: string
      GAROON_BRANCH_NAME:
        type: string
      ARCHIVE_FOLDER:
        description: 'ARCHIVE_FOLDER (e.g: 202305100817_1172324)'
        type: string
      GAROON_ARCHIVE:
        description: 'GAROON_ARCHIVE (e.g: garoon-GRF23.5_1172324.tgz)'
        type: string
      GAROON_TYPE:
        type: choice
        default: 'Cloud'
        options:
          - 'Cloud'
          - 'Large Scale Linux'
          - 'Normal Linux'
          - 'Normal Windows'
      IS_SET_UP_MAIL_ACCOUNT:
        default: true
        type: boolean
      IS_CREATE_MAIL_FOLDER:
        default: true
        type: boolean
      force_recreate_service_set:
        default: true
        type: boolean

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Environment Variables
        uses: actions/github-script@v6
        with:
          script: |
            const envInfo = require("./.github/workflows/schedule.json");
            const commonInfo = envInfo.common;
            const branchInfo = envInfo["${{ github.event.schedule }}"]
            
            core.exportVariable("ADMIN_USERNAME", commonInfo.ADMIN_USERNAME);
            core.exportVariable("PASSWORD", commonInfo.PASSWORD);
            core.exportVariable("SERVICE_SET", branchInfo.service_set);
            core.exportVariable("TESTING_HOST", branchInfo.testing_host);
      - name: Update Environment Variables From Manual Trigger
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ADMIN_USERNAME', "${{ github.event.inputs.ADMIN_USERNAME }}");
            core.exportVariable('PASSWORD', "${{ github.event.inputs.PASSWORD }}");
      - name: Sprint Env
        run: |
          echo "${{ env.ADMIN_USERNAME }}"
          echo "${{ env.PASSWORD }}"
          echo "${{ env.SERVICE_SET }}"
          echo "${{ env.TESTING_HOST }}"
