name: Run Name
run-name: ${{ env["0 21 * * 1-4,0"] }} - Test

env:
  - "0 21 * * 1-4,0": "F23.5"
  - "0 21 * * 1-4,0": "F23.7"

on:
  on_push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: datdo178/github-actions
          ref: test
      - run: echo "${{ env["0 21 * * 1-4,0"] }}"
      - run: ls
