name: Run Name
run-name: "$edition - ${{ github.event.inputs.edition }} - ABC"

env:
  edition: 'abc'

on:
  push:
  workflow_dispatch:
    inputs:
      edition:
        required: false
        description: 'CONFIGURED_TESTING_BRANCH - If select a specific branch, you can ignore variables below (default values will be applied)'
        default: 'F23.5'
        type: 'choice'
        options:
          - 'None'
          - 'F23.5'
          - 'F23.6'
          - 'F23.7'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: datdo178/github-actions
          ref: test
      - run: echo "${{ github.inputs.edition }}"
      - run: ls
